language: node_js
node_js:
  - '4.1'
  - '4.0'
  - '0.12'
  - '0.11'
  - '0.10'
  - '0.8'
  - '0.6'
  - 'iojs'
services:
  - postgresql
before_script:
  - psql -c 'create database ceap_test;' -U postgres
  - cp config/config.json.example config/config.json
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - TRAVIS=travis CXX=g++-4.8
